# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app for Pages

on:
  push: 
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Generate correct docker tag
      id: gen_tags
      run: |
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          TAG='latest'
        else
          TAG='alpha'
        fi
          echo '::set-output name=tag::'$TAG
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Prepare environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
          npm install
          npm install -g @ionic/cli
    - name: Build App & Workspace files
      run: |
        ionic build --prod
    - name: Build and push container
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/ombi-mobile:${{ steps.gen_tags.outputs.tag }}
#    - name: Deploy update
#      uses: joelwmale/webhook-action@master
#      with:
#        url: ${{ secrets.WEBHOOK_URL }}
#        headers: '{"x-api-key": "${{ secrets.WEBHOOK_API_KEY }}"}'
#        body: '{"container": "ombi-mobile-${{ steps.gen_tags.outputs.tag }}"}'
